### ISSUE TITLE
opendistro-sql v0.10.0.0 not available in Repositories

### ISSUE THREAD

**Issue by rlk5546** [opendistro-for-elasticsearch/sql#211]
Manual install of opendistroforelasticsearch=0.10.0.0 fails due to missing opendistro-sql=v0.10.0 dependency.

OS:  Ubuntu 18.04 LTS

> $apt-cache policy opendistro-sql
> opendistro-sql:
>   Installed: (none)
>   Candidate: 1.2.0.0-1
>   Version table:
>      1.2.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.1.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.0.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.9.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.8.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages

I know I'm asking for an earlier version.  Please restore the opendistro-sql=v0.10.0 package to the repo

Thanks

rlk

**Comment by abbashus** [comment]
Thanks for reporting. We will look into this and get back soon.

**Comment by abbashus** [comment]
@rlk5546 Can you provide the steps used for the manual installation. We want to reproduce at our end. Thanks.

**Comment by rlk5546** [comment]
OS: Ubuntu 18.04 LTS
Assuming Repo's are added:

> $apt update
>

Find available versions:

> $apt-cache policy opendistro*
> opendistro-performance-analyzer:
>   Installed: (none)
>   Candidate: 1.2.0.0-1
>   Version table:
>      1.2.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.1.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.0.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.10.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.9.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.8.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
> opendistro-alerting:
>   Installed: (none)
>   Candidate: 1.2.0.0-1
>   Version table:
>      1.2.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.1.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.0.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.10.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.9.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.8.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
> opendistroforelasticsearch:
>   Installed: (none)
>   Candidate: 1.2.0-1
>   Version table:
>      1.2.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.1.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.0.2-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.0.1-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.10.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.9.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.8.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
> opendistro-job-scheduler:
>   Installed: (none)
>   Candidate: 1.2.0.0-1
>   Version table:
>      1.2.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.1.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.0.0.1-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.0.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
> opendistro-sql:
>   Installed: (none)
>   Candidate: 1.2.0.0-1
>   Version table:
>      1.2.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.1.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.0.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.9.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.8.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
> opendistro-security:
>   Installed: (none)
>   Candidate: 1.2.0.0-0
>   Version table:
>      1.2.0.0-0 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.1.0.0-0 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.0.0.2-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.0.0.1-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.0.0.0-0 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.10.0.0-0 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.9.0.0-0 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.8.0.0-1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
> opendistroforelasticsearch-kibana:
>   Installed: (none)
>   Candidate: 1.2.0
>   Version table:
>      1.2.0 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.1.0 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.0.2 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.0.1 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      1.0.0 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.10.0 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.9.0 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
>      0.8.0 500
>         500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages

Install Opendistro v0.10 manually, (the debian/ubuntu way)
(there is no version 0.10.x for opendistro-sql and opendistro-job-scheduler so they are not included in the command below)

> $apt install opendistro-performance-analyzer=0.10.0.0-1 opendistro-alerting=0.10.0.0-1 opendistro-security=0.10.0.0-0 opendistroforelasticsearch=0.10.0-1
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  opendistroforelasticsearch : Depends: opendistro-sql (>= 0.10.0) but it is not going to be installed
>                               Depends: opendistro-sql (< 0.10.1) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.


- The above command works fine with v0.9.x.
- Manual install of opendistroforelasticsearch v0.10 package fails due to missing opendistro-sql v0.10.x package.
- Installing each package individually, omitting opendistro-sql, works fine, but the security tab in Kibana is broken (different issue that I will confirm if this can be fixed)
- if opendistroforelasticsearch is a meta-package, you could remove the dependency.

Thank you for speedy responses

rlk

**Comment by dai-chen** [comment]
I double checked and confirmed deb artifact for SQL 0.10 is missing in published repository while other plugin doesn't have the issue. After investigation, I found that `buildDeb` task is missing on our 0.10 branch for some reason: https://github.com/opendistro-for-elasticsearch/sql/blob/opendistro-0.10/build.gradle#L202.

**Comment by dai-chen** [comment]
I think we need to add `buildDeb` gradle task to 0.10 branch and publish deb artifact.

**Comment by dai-chen** [comment]
@rishabh6788 Could you give me some help? I can modify `build.gradle` if needed but I'm not sure how to publish it for SQL.

**Comment by danielrheinbay** [comment]
I have cherry-picked 16d399c and ed6c046 which add the missing buildDeb function. See Pull Request #269.

**Comment by abbashus** [comment]
Fixed by #269

**Comment by danielrheinbay** [comment]
@abbashus , you have closed this issue, but the package appears still missing in the repository:
Assuming `$ apt update`, then list available versions:
```$apt-cache policy opendistro-sql
opendistro-sql:
  Installed: (none)
  Candidate: 1.2.1.0-1
  Version table:
     1.2.1.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
     1.2.0.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
     1.1.0.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
     1.0.0.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
     0.9.0.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
     0.8.0.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
```

Are there any issues building the package? Are build jobs triggered automagically, or do we need someone to trigger the build job and push the packages...? How can we move forward?

**Comment by dai-chen** [comment]
@danielrheinbay Sorry for the confusion.

@rishabh6788 Any chance to upload the artifact since we've have the fix for `buildDeb` Gradle task in SQL 0.10.

**Comment by lps-rocks** [comment]
This is still a problem. It's missing from the repository still.

**Comment by dai-chen** [comment]
@rishabh6788 When do we expect to fix this issue? It has been pending for long. Cc @anirudha

**Comment by danielrheinbay** [comment]
@anirudha , you have closed this issue, but the package appears still missing in the repository:
Assuming `$ apt update`, then list available versions:
```$apt-cache policy opendistro-sql
opendistro-sql:
  Installed: (none)
  Candidate: 1.9.0.0-1
  Version table:
     1.9.0.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
     1.8.0.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
     1.7.0.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
     1.6.0.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
     1.4.0.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
     1.3.0.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
     1.2.1.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
     1.2.0.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
     1.1.0.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
     1.0.0.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
     0.9.0.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
     0.8.0.0-1 500
        500 https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
```

Are there any issues building the package? Are build jobs triggered automagically, or do we need someone to trigger the build job and push the packages...? How can we move forward?

@dai-chen, I'd appreciate if you could maybe shed some light why this issue was closed twice without being solved, despite the source code having been fixed by #269 back in November 2019. I am sorry to sound insisting, yet I would really like to see this solved :)
