### ISSUE TITLE
CSV export of JSON values

### ISSUE THREAD

**Issue by kakulukia** [opendistro-for-elasticsearch/sql#40]
GET _opendistro/_sql?format=csv

is not exporting quoted values and thus having JSON with additional commas in one of the exported fields will kill the following fields order. 
Can quoted output be forced somehow?

**Comment by dai-chen** [comment]
> GET _opendistro/_sql?format=csv
> 
> is not exporting quoted values and thus having JSON with additional commas in one of the exported fields will kill the following fields order.
> Can quoted output be forced somehow?

Could you please provide a sample of your data and actual output (and maybe expected output as well)? Thanks!

**Comment by kakulukia** [comment]
I cant share our projects data, but let me give one small example:

    {
      "one", "one",
      "two": [1, 2],
      "three": {"another": true, "dict": false}
    }

This will result in (spreading the data in 5 rows rather than the intended 3 - and also breaking it):

    one,two,three
    one,[1, 2], {another=true, dict=false}

But it should result in at least:

    one,two,three
    "one","[1, 2]","{another=true, dict=false}"

There might even be a way of keeping the JSON intact, but i dont mind that much.

**Comment by arsen-es** [comment]
The quotation part is required by [CSV spec](https://tools.ietf.org/html/rfc4180) (see 2.6).

As for nested objects, I did not find a standard for conversion, but I checked some implementations and all are flattening the JSON by putting the fully qualified path to the field in the header, e.g. in the provided example the headers will be the following (the delimiter between the path terms is also a subject of preference, some use `/` instead of `_`):
`one,two,three_another,three_dict`.

Another option is flattening the arrays as well:
`one,two_0,two_1,three_another,three_dict`.

**Comment by kakulukia** [comment]
Please dont alter the data, since whats exported now can still be parsed in a nice way. Please, just add the quotation, so that the exported csv is actually valid.

**Comment by arsen-es** [comment]
Resolved by #42

**Comment by kakulukia** [comment]
Sadly i just tested a newer version of Kibana 6.7.1 only to see that the CSV export got worse than before. Its still not featuring quoted values, but lists that are separated by space now. Having spaces in the values, this makes it very hard to fix the existing export data. :(

Actual JSON values are untouched as far as i can tell.
Here is an example of an exported list: "[[value-1 value-2]]"

How can i see which version of SQL is included in my Kibana release?

**Comment by kakulukia** [comment]
Ignore the previous post, our Kibana release still uses the old SQL version and the changed list format results from a now broken data import by our reports team.
Reporting back when i can have a look at the latest version. Sorry for the confusion!

**Comment by dai-chen** [comment]
> Ignore the previous post, our Kibana release still uses the old SQL version and the changed list format results from a now broken data import by our reports team.
> Reporting back when i can have a look at the latest version. Sorry for the confusion!

Sure, no worries. Let us know if any other issue. Thanks!

**Comment by horacimacias** [comment]
Thanks for looking at this, I think the behaviour now is better but unfortunately it looks like there are still some cases to fix here.

The values containing commas are now quoted (which is good) but then the values containing quotes (in the value, not as leading/trailing characters) need to be escaped as well.

As an example, I created this document:

> {
>   "one":"one",
>   "two": [1, 2],
>   "three": {"another": true, "dict": false, "quoted":"this \"value\" contains quotes" }
> }

An sql/csv export (_opendistro/_sql?format=csv) gives me the following:

> one,two,three
> one,"[1, 2]","{quoted=this "value" contains quotes, another=true, dict=false}"

If I try to import this in Excel as CSV (please let me know if there is any more standard way of validating csv) the results are not the expected ones.
Also tried csvlint.io and complains about _Stray quote on row 4_

According to CSV spec _If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote_

If I take the output of csv export and "fix" it by escaping the double quotes with another double quote:

> one,two,three
> one,"[1, 2]","{quoted=this ""value"" contains quotes, another=true, dict=false}"

then Excel is happy and so is csvlint.io

**Comment by dai-chen** [comment]
Reopening for more investigation.

**Comment by arsen-es** [comment]
Apologies for not complying with the CSV spec, will submit a PR with a fix soon.
